// src/app/config/filterData.js

// ১. প্রপার্টি টাইপ লিস্ট (আবাসিক ও বাণিজ্যিক)
export const propertyTypes = [
  // Residential (আবাসিক)
  { id: 'flat', name: 'Flat / Apartment', bnName: 'ফ্ল্যাট / অ্যাপার্টমেন্ট', category: 'residential' },
  { id: 'sublet', name: 'Sublet (Family/Female)', bnName: 'সাবলেট (ফ্যামিলি/মহিলা)', category: 'residential' },
  { id: 'bachelor', name: 'Bachelor / Mess Room', bnName: 'ব্যাচেলর / মেস রুম', category: 'residential' },
  { id: 'tinshed', name: 'Tin-shed House', bnName: 'টিনশেড বাসা', category: 'residential' },
  { id: 'hostel', name: 'Hostel / Seat Rent', bnName: 'হোস্টেল / সিট ভাড়া', category: 'residential' },
  { id: 'duplex', name: 'Duplex / Full House', bnName: 'ডুপ্লেক্স / পুরো বাড়ি', category: 'residential' },

  // Commercial (বাণিজ্যিক)
  { id: 'office', name: 'Office Space', bnName: 'অফিস স্পেস', category: 'commercial' },
  { id: 'shop', name: 'Shop / Showroom', bnName: 'দোকান / শোরুম', category: 'commercial' },
  { id: 'warehouse', name: 'Warehouse / Godown', bnName: 'গুদাম / গোডাউন', category: 'commercial' },
  { id: 'garage', name: 'Garage / Parking Space', bnName: 'গ্যারেজ / পার্কিং স্পেস', category: 'commercial' },
];

// ২. বাজেট রেঞ্জ
export const budgetRanges = [
  { label: '৳ 3k - 7k (৩ - ৭ হাজার)', min: 3000, max: 7000 },
  { label: '৳ 8k - 15k (৮ - ১৫ হাজার)', min: 8000, max: 15000 },
  { label: '৳ 16k - 30k (১৬ - ৩০ হাজার)', min: 16000, max: 30000 },
  { label: '৳ 35k - 60k (৩৫ - ৬০ হাজার)', min: 35000, max: 60000 },
  { label: '৳ 60k - 1 Lakh+ (৬০ হাজার - ১ লাখ+)', min: 60000, max: 1000000 },
];

// ৩. বাংলাদেশের ৮টি বিভাগ, ৬৪ জেলা এবং সমস্ত থানা ও উপজেলা ডাটাবেস
export const locationsData = {
  // ৮টি বিভাগ
  divisions: [
    { id: 'dhaka', name: 'Dhaka', bnName: 'ঢাকা' },
    { id: 'chattogram', name: 'Chattogram', bnName: 'চট্টগ্রাম' },
    { id: 'rajshahi', name: 'Rajshahi', bnName: 'রাজশাহী' },
    { id: 'khulna', name: 'Khulna', bnName: 'খুলনা' },
    { id: 'barishal', name: 'Barishal', bnName: 'বরিশাল' },
    { id: 'sylhet', name: 'Sylhet', bnName: 'সিলেট' },
    { id: 'rangpur', name: 'Rangpur', bnName: 'রংপুর' },
    { id: 'mymensingh', name: 'Mymensingh', bnName: 'ময়মনসিংহ' },
  ],

  // বিভাগ অনুযায়ী ৬৪টি জেলা
  districts: {
    dhaka: [
      { id: 'dhaka-city', name: 'Dhaka', bnName: 'ঢাকা' },
      { id: 'gazipur', name: 'Gazipur', bnName: 'গাজীপুর' },
      { id: 'narayanganj', name: 'Narayanganj', bnName: 'নারায়ণগঞ্জ' },
      { id: 'narsingdi', name: 'Narsingdi', bnName: 'নরসিংদী' },
      { id: 'tangail', name: 'Tangail', bnName: 'টাঙ্গাইল' },
      { id: 'manikganj', name: 'Manikganj', bnName: 'মানিকগঞ্জ' },
      { id: 'munshiganj', name: 'Munshiganj', bnName: 'মুন্সীগঞ্জ' },
      { id: 'faridpur', name: 'Faridpur', bnName: 'ফরিদপুর' },
      { id: 'gopalganj', name: 'Gopalganj', bnName: 'গোপালগঞ্জ' },
      { id: 'madaripur', name: 'Madaripur', bnName: 'মাদারীপুর' },
      { id: 'rajbari', name: 'Rajbari', bnName: 'রাজবাড়ী' },
      { id: 'shariatpur', name: 'Shariatpur', bnName: 'শরীয়তপুর' },
      { id: 'kishoreganj', name: 'Kishoreganj', bnName: 'কিশোরগঞ্জ' },
    ],
    chattogram: [
      { id: 'chattogram-city', name: 'Chattogram', bnName: 'চট্টগ্রাম' },
      { id: 'coxsbazar', name: "Cox's Bazar", bnName: 'কক্সবাজার' },
      { id: 'cumilla', name: 'Cumilla', bnName: 'কুমিল্লা' },
      { id: 'feni', name: 'Feni', bnName: 'ফেনী' },
      { id: 'brahmanbaria', name: 'Brahmanbaria', bnName: 'ব্রাহ্মণবাড়িয়া' },
      { id: 'noakhali', name: 'Noakhali', bnName: 'নোয়াখালী' },
      { id: 'chandpur', name: 'Chandpur', bnName: 'চাঁদপুর' },
      { id: 'lakshmipur', name: 'Lakshmipur', bnName: 'লক্ষ্মীপুর' },
      { id: 'rangamati', name: 'Rangamati', bnName: 'রাঙ্গামাটি' },
      { id: 'bandarban', name: 'Bandarban', bnName: 'বান্দরবান' },
      { id: 'khagrachhari', name: 'Khagrachhari', bnName: 'খাগড়াছড়ি' },
    ],
    rajshahi: [
      { id: 'rajshahi-city', name: 'Rajshahi', bnName: 'রাজশাহী' },
      { id: 'bogura', name: 'Bogura', bnName: 'বগুড়া' },
      { id: 'pabna', name: 'Pabna', bnName: 'পাবনা' },
      { id: 'sirajganj', name: 'Sirajganj', bnName: 'সিরাজগঞ্জ' },
      { id: 'naogaon', name: 'Naogaon', bnName: 'নওগাঁ' },
      { id: 'natore', name: 'Natore', bnName: 'নাটোর' },
      { id: 'chapainawabganj', name: 'Chapainawabganj', bnName: 'চাঁপাইনবাবগঞ্জ' },
      { id: 'joypurhat', name: 'Joypurhat', bnName: 'জয়পুরহাট' },
    ],
    khulna: [
      { id: 'khulna-city', name: 'Khulna', bnName: 'খুলনা' },
      { id: 'jashore', name: 'Jashore', bnName: 'যশোর' },
      { id: 'kushtia', name: 'Kushtia', bnName: 'কুষ্টিয়া' },
      { id: 'satkhira', name: 'Satkhira', bnName: 'সাতক্ষীরা' },
      { id: 'bagerhat', name: 'Bagerhat', bnName: 'বাগেরহাট' },
      { id: 'jhenaidah', name: 'Jhenaidah', bnName: 'ঝিনাইদহ' },
      { id: 'chuadanga', name: 'Chuadanga', bnName: 'চুয়াডাঙ্গা' },
      { id: 'magura', name: 'Magura', bnName: 'মাগুরা' },
      { id: 'meherpur', name: 'Meherpur', bnName: 'মেহেরপুর' },
      { id: 'narail', name: 'Narail', bnName: 'নড়াইল' },
    ],
    barishal: [
      { id: 'barishal-city', name: 'Barishal', bnName: 'বরিশাল' },
      { id: 'bhola', name: 'Bhola', bnName: 'ভোলা' },
      { id: 'patuakhali', name: 'Patuakhali', bnName: 'পটুয়াখালী' },
      { id: 'pirojpur', name: 'Pirojpur', bnName: 'পিরোজপুর' },
      { id: 'barguna', name: 'Barguna', bnName: 'বরগুনা' },
      { id: 'jhalokathi', name: 'Jhalokathi', bnName: 'ঝালকাঠি' },
    ],
    sylhet: [
      { id: 'sylhet-city', name: 'Sylhet', bnName: 'সিলেট' },
      { id: 'moulvibazar', name: 'Moulvibazar', bnName: 'মৌলভীবাজার' },
      { id: 'habiganj', name: 'Habiganj', bnName: 'হবিগঞ্জ' },
      { id: 'sunamganj', name: 'Sunamganj', bnName: 'সুনামগঞ্জ' },
    ],
    rangpur: [
      { id: 'rangpur-city', name: 'Rangpur', bnName: 'রংপুর' },
      { id: 'dinajpur', name: 'Dinajpur', bnName: 'দিনাজপুর' },
      { id: 'gaibandha', name: 'Gaibandha', bnName: 'গাইবান্ধা' },
      { id: 'kurigram', name: 'Kurigram', bnName: 'কুড়িগ্রাম' },
      { id: 'lalmonirhat', name: 'Lalmonirhat', bnName: 'লালমনিরহাট' },
      { id: 'nilphamari', name: 'Nilphamari', bnName: 'নীলফামারী' },
      { id: 'panchagarh', name: 'Panchagarh', bnName: 'পঞ্চগড়' },
      { id: 'thakurgaon', name: 'Thakurgaon', bnName: 'ঠাকুরগাঁও' },
    ],
    mymensingh: [
      { id: 'mymensingh-city', name: 'Mymensingh', bnName: 'ময়মনসিংহ' },
      { id: 'jamalpur', name: 'Jamalpur', bnName: 'জামালপুর' },
      { id: 'netrokona', name: 'Netrokona', bnName: 'নেত্রকোণা' },
      { id: 'sherpur', name: 'Sherpur', bnName: 'শেরপুর' },
    ],
  },

  // ৬৪টি জেলার সকল থানা ও উপজেলা (ইংরেজি ও বাংলা নামসহ)
  thanas: {
    // ==================== ঢাকা বিভাগ (DHAKA DIVISION) ====================
    'dhaka-city': [
      { name: 'Dhanmondi', bnName: 'ধানমন্ডি' },
      { name: 'Gulshan', bnName: 'গুলশান' },
      { name: 'Banani', bnName: 'বনানী' },
      { name: 'Uttara', bnName: 'উত্তরা' },
      { name: 'Mirpur', bnName: 'মিরপুর' },
      { name: 'Mohammadpur', bnName: 'মোহাম্মদপুর' },
      { name: 'Badda', bnName: 'বাড্ডা' },
      { name: 'Bashundhara R/A', bnName: 'বসুন্ধরা আ/এ' },
      { name: 'Motijheel', bnName: 'মতিঝিল' },
      { name: 'Paltan', bnName: 'পল্টন' },
      { name: 'Khilgaon', bnName: 'খিলগাঁও' },
      { name: 'Rampura', bnName: 'রামপুরা' },
      { name: 'Tejgaon', bnName: 'তেজগাঁও' },
      { name: 'Old Dhaka (Lalbagh/Sutrapur)', bnName: 'পুরান ঢাকা (লালবাগ/সূত্রাপুর)' },
      { name: 'Jatrabari', bnName: 'যাত্রাবাড়ী' },
      { name: 'Kadamtali', bnName: 'কদমতলী' },
      { name: 'Shyamoli', bnName: 'শ্যামলী' },
      { name: 'Kalyanpur', bnName: 'কল্যাণপুর' },
      { name: 'Malibagh', bnName: 'মালিবাগ' },
      { name: 'Moghbazar', bnName: 'মগবাজার' },
      { name: 'Savar', bnName: 'সাভার' },
      { name: 'Keraniganj', bnName: 'কেরানীগঞ্জ' },
      { name: 'Dhamrai', bnName: 'ধামরাই' },
      { name: 'Nawabganj', bnName: 'নবাবগঞ্জ' },
      { name: 'Dohar', bnName: 'দোহার' },
    ],
    'gazipur': [
      { name: 'Gazipur Sadar', bnName: 'গাজীপুর সদর' },
      { name: 'Tongi', bnName: 'টঙ্গী' },
      { name: 'Kaliakair', bnName: 'কালিয়াকৈর' },
      { name: 'Sreepur', bnName: 'শ্রীপুর' },
      { name: 'Kapasia', bnName: 'কাপাসিয়া' },
      { name: 'Kaliganj', bnName: 'কালীগঞ্জ' },
    ],
    'narayanganj': [
      { name: 'Narayanganj Sadar', bnName: 'নারায়ণগঞ্জ সদর' },
      { name: 'Bandar', bnName: 'বন্দর' },
      { name: 'Rupganj', bnName: 'রূপগঞ্জ' },
      { name: 'Araihazar', bnName: 'আড়াইহাজার' },
      { name: 'Sonargaon', bnName: 'সোনারগাঁও' },
      { name: 'Siddhirganj', bnName: 'সিদ্ধিরগঞ্জ' },
      { name: 'Fatullah', bnName: 'ফতুল্লা' },
    ],
    'narsingdi': [
      { name: 'Narsingdi Sadar', bnName: 'নরসিংদী সদর' },
      { name: 'Palash', bnName: 'পলাশ' },
      { name: 'Shibpur', bnName: 'শিবপুর' },
      { name: 'Raipura', bnName: 'রায়পুরা' },
      { name: 'Belabo', bnName: 'বেলাবো' },
      { name: 'Monohardi', bnName: 'মনোহরদী' },
    ],
    'tangail': [
      { name: 'Tangail Sadar', bnName: 'টাঙ্গাইল সদর' },
      { name: 'Mirzapur', bnName: 'মির্জাপুর' },
      { name: 'Kalihati', bnName: 'কালিহাতী' },
      { name: 'Ghatail', bnName: 'ঘাটাইল' },
      { name: 'Madhupur', bnName: 'মধুপুর' },
      { name: 'Sakhipur', bnName: 'সখিপুর' },
      { name: 'Gopalpur', bnName: 'গোপালপুর' },
      { name: 'Delduar', bnName: 'দেলদুয়ার' },
      { name: 'Bhuapur', bnName: 'ভূঞাপুর' },
      { name: 'Basail', bnName: 'বাসাইল' },
      { name: 'Nagarpur', bnName: 'নাগরপুর' },
      { name: 'Dhanbari', bnName: 'ধনবাড়ী' },
    ],
    'manikganj': [
      { name: 'Manikganj Sadar', bnName: 'মানিকগঞ্জ সদর' },
      { name: 'Singair', bnName: 'সিংগাইর' },
      { name: 'Saturia', bnName: 'সাটুরিয়া' },
      { name: 'Ghior', bnName: 'ঘিওর' },
      { name: 'Shivalaya', bnName: 'শিবালয়' },
      { name: 'Daulatpur', bnName: 'দৌলতপুর' },
      { name: 'Harirampur', bnName: 'হরিরামপুর' },
    ],
    'munshiganj': [
      { name: 'Munshiganj Sadar', bnName: 'মুন্সীগঞ্জ সদর' },
      { name: 'Sreenagar', bnName: 'শ্রীনগর' },
      { name: 'Sirajdikhan', bnName: 'সিরাজদিখান' },
      { name: 'Louhajang', bnName: 'লৌহজং' },
      { name: 'Tongibari', bnName: 'টঙ্গীবাড়ী' },
      { name: 'Gazaria', bnName: 'গজারিয়া' },
    ],
    'faridpur': [
      { name: 'Faridpur Sadar', bnName: 'ফরিদপুর সদর' },
      { name: 'Boalmari', bnName: 'বোয়ালমারী' },
      { name: 'Bhanga', bnName: 'ভাঙ্গা' },
      { name: 'Alfadanga', bnName: 'আলফাডাঙ্গা' },
      { name: 'Madhukhali', bnName: 'মধুখালী' },
      { name: 'Nagarkanda', bnName: 'নগরকান্দা' },
      { name: 'Sadarpur', bnName: 'সদরপুর' },
      { name: 'Saltha', bnName: 'সালথা' },
      { name: 'Charbhadrasan', bnName: 'চরভদ্রাসন' },
    ],
    'gopalganj': [
      { name: 'Gopalganj Sadar', bnName: 'গোপালগঞ্জ সদর' },
      { name: 'Kashiani', bnName: 'কাশিয়ানী' },
      { name: 'Kotalipara', bnName: 'কোটালীপাড়া' },
      { name: 'Muksudpur', bnName: 'মুকসুদপুর' },
      { name: 'Tungipara', bnName: 'টুঙ্গিপাড়া' },
    ],
    'madaripur': [
      { name: 'Madaripur Sadar', bnName: 'মাদারীপুর সদর' },
      { name: 'Kalkini', bnName: 'কালকিনি' },
      { name: 'Rajoir', bnName: 'রাজৈর' },
      { name: 'Shibchar', bnName: 'শিবচর' },
      { name: 'Dasar', bnName: 'ডাসার' },
    ],
    'rajbari': [
      { name: 'Rajbari Sadar', bnName: 'রাজবাড়ী সদর' },
      { name: 'Baliakandi', bnName: 'বালিয়াকান্দি' },
      { name: 'Goalandaghat', bnName: 'গোয়ালন্দঘাট' },
      { name: 'Pangsha', bnName: 'পাংশা' },
      { name: 'Kalukhali', bnName: 'কালুখালী' },
    ],
    'shariatpur': [
      { name: 'Shariatpur Sadar', bnName: 'শরীয়তপুর সদর' },
      { name: 'Damudya', bnName: 'ডামুড্যা' },
      { name: 'Naria', bnName: 'নড়িয়া' },
      { name: 'Janjira', bnName: 'জাজিরা' },
      { name: 'Bhedarganj', bnName: 'ভেদরগঞ্জ' },
      { name: 'Gosairhat', bnName: 'গোসাইরহাট' },
    ],
    'kishoreganj': [
      { name: 'Kishoreganj Sadar', bnName: 'কিশোরগঞ্জ সদর' },
      { name: 'Bhairab', bnName: 'ভৈরব' },
      { name: 'Bajitpur', bnName: 'বাজিতপুর' },
      { name: 'Katiadi', bnName: 'কটিয়াদী' },
      { name: 'Kuliarchar', bnName: 'কুলিয়ারচর' },
      { name: 'Pakundia', bnName: 'পাকুন্দিয়া' },
      { name: 'Hossainpur', bnName: 'হোসেনপুর' },
      { name: 'Karimganj', bnName: 'করিমগঞ্জ' },
      { name: 'Tarail', bnName: 'তাড়াইল' },
      { name: 'Itna', bnName: 'ইটনা' },
      { name: 'Mithamoin', bnName: 'মিঠামইন' },
      { name: 'Austagram', bnName: 'অষ্টগ্রাম' },
      { name: 'Nikli', bnName: 'নিকলী' },
    ],

    // ==================== চট্টগ্রাম বিভাগ (CHATTOGRAM DIVISION) ====================
    'chattogram-city': [
      { name: 'Agrabad', bnName: 'আগ্রাবাদ' },
      { name: 'GEC Circle', bnName: 'জিইসি মোড়' },
      { name: 'Nasirabad', bnName: 'নাসিরাবাদ' },
      { name: 'Halishahar', bnName: 'হালিশহর' },
      { name: 'Khulshi', bnName: 'খুলশী' },
      { name: 'Panchlaish', bnName: 'পাঁচলাইশ' },
      { name: 'Kotwali', bnName: 'কোতোয়ালী' },
      { name: 'Pahartali', bnName: 'পাহাড়তলী' },
      { name: 'Bakalia', bnName: 'বাকলিয়া' },
      { name: 'Chandgaon', bnName: 'চান্দগাঁও' },
      { name: 'Patenga', bnName: 'পতেঙ্গা' },
      { name: 'Bayezid', bnName: 'বায়েজিদ' },
      { name: 'Hathazari', bnName: 'হাটহাজারী' },
      { name: 'Sitakunda', bnName: 'সীতাকুণ্ড' },
      { name: 'Mirsharai', bnName: 'মীরসরাই' },
      { name: 'Patiya', bnName: 'পটিয়া' },
      { name: 'Raozan', bnName: 'রাউজান' },
      { name: 'Rangunia', bnName: 'রাঙ্গুনিয়া' },
      { name: 'Fatikchhari', bnName: 'ফটিকছড়ি' },
      { name: 'Boalkhali', bnName: 'বোয়ালখালী' },
      { name: 'Anwara', bnName: 'আনোয়ারা' },
      { name: 'Chandanaish', bnName: 'চন্দনাইশ' },
      { name: 'Lohagara', bnName: 'লোহাগাড়া' },
      { name: 'Satkania', bnName: 'সাতকানিয়া' },
      { name: 'Banshkhali', bnName: 'বাঁশখালী' },
      { name: 'Karnaphuli', bnName: 'কর্ণফুলী' },
      { name: 'Sandwip', bnName: 'সন্দ্বীপ' },
    ],
    'coxsbazar': [
      { name: 'Coxs Bazar Sadar', bnName: 'কক্সবাজার সদর' },
      { name: 'Ramu', bnName: 'রামু' },
      { name: 'Chakaria', bnName: 'চকোরিয়া' },
      { name: 'Teknaf', bnName: 'টেকনাফ' },
      { name: 'Ukhiya', bnName: 'উখিয়া' },
      { name: 'Pekua', bnName: 'পেকুয়া' },
      { name: 'Kutubdia', bnName: 'কুতুবদিয়া' },
      { name: 'Maheshkhali', bnName: 'মহেশখালী' },
      { name: 'Eidgaon', bnName: 'ঈদগাঁও' },
    ],
    'cumilla': [
      { name: 'Cumilla Adarsha Sadar', bnName: 'কুমিল্লা আদর্শ সদর' },
      { name: 'Cumilla Sadar Dakshin', bnName: 'কুমিল্লা সদর দক্ষিণ' },
      { name: 'Laksam', bnName: 'লাকসাম' },
      { name: 'Debidwar', bnName: 'দেবীদ্বার' },
      { name: 'Chandina', bnName: 'চান্দিনা' },
      { name: 'Burichang', bnName: 'বুড়িচং' },
      { name: 'Brahmanpara', bnName: 'ব্রাহ্মণপাড়া' },
      { name: 'Chauddagram', bnName: 'চৌদ্দগ্রাম' },
      { name: 'Daudkandi', bnName: 'দাউদকান্দি' },
      { name: 'Homna', bnName: 'হোমনা' },
      { name: 'Muradnagar', bnName: 'মুরাদনগর' },
      { name: 'Barura', bnName: 'বরুড়া' },
      { name: 'Titas', bnName: 'তিতাস' },
      { name: 'Meghna', bnName: 'মেঘনা' },
      { name: 'Monohargonj', bnName: 'মনোহরগঞ্জ' },
      { name: 'Nangalkot', bnName: 'নাঙ্গলকোট' },
      { name: 'Lalmai', bnName: 'লালমাই' },
    ],
    'feni': [
      { name: 'Feni Sadar', bnName: 'ফেনী সদর' },
      { name: 'Daganbhuiyan', bnName: 'দাগনভূঞা' },
      { name: 'Chhagalnaiya', bnName: 'ছাগলনাইয়া' },
      { name: 'Parshuram', bnName: 'পরশুরাম' },
      { name: 'Fulgazi', bnName: 'ফুলগাজী' },
      { name: 'Sonagazi', bnName: 'সোনাগাজী' },
    ],
    'brahmanbaria': [
      { name: 'Brahmanbaria Sadar', bnName: 'ব্রাহ্মণবাড়িয়া সদর' },
      { name: 'Ashuganj', bnName: 'আশুগঞ্জ' },
      { name: 'Sarail', bnName: 'সরাইল' },
      { name: 'Kasba', bnName: 'কসবা' },
      { name: 'Akhaura', bnName: 'আখাউড়া' },
      { name: 'Nabinagar', bnName: 'নবীনগর' },
      { name: 'Bancharampur', bnName: 'বাঞ্ছারামপুর' },
      { name: 'Bijoynagar', bnName: 'বিজয়নগর' },
      { name: 'Nasirnagar', bnName: 'নাসিরনগর' },
    ],
    'noakhali': [
      { name: 'Noakhali Sadar (Sudharam)', bnName: 'নোয়াখালী সদর (সুধারাম)' },
      { name: 'Begumganj', bnName: 'বেগমগঞ্জ' },
      { name: 'Chatkhil', bnName: 'চাটখিল' },
      { name: 'Companiganj', bnName: 'কোম্পানীগঞ্জ' },
      { name: 'Hatiya', bnName: 'হাতিয়া' },
      { name: 'Senbagh', bnName: 'সেনবাগ' },
      { name: 'Sonaimuri', bnName: 'সোনাইমুড়ী' },
      { name: 'Subarnachar', bnName: 'সুবর্ণচর' },
      { name: 'Kabirhat', bnName: 'কবিরহাট' },
    ],
    'chandpur': [
      { name: 'Chandpur Sadar', bnName: 'চাঁদপুর সদর' },
      { name: 'Hajiganj', bnName: 'হাজীগঞ্জ' },
      { name: 'Faridganj', bnName: 'ফরিদগঞ্জ' },
      { name: 'Matlab Uttar', bnName: 'মতলব উত্তর' },
      { name: 'Matlab Dakshin', bnName: 'মতলব দক্ষিণ' },
      { name: 'Shahrasti', bnName: 'শাহরাস্তি' },
      { name: 'Kachua', bnName: 'কচুয়া' },
      { name: 'Haimchar', bnName: 'হাইমচর' },
    ],
    'lakshmipur': [
      { name: 'Lakshmipur Sadar', bnName: 'লক্ষ্মীপুর সদর' },
      { name: 'Raipur', bnName: 'রায়পুর' },
      { name: 'Ramganj', bnName: 'রামগঞ্জ' },
      { name: 'Ramgati', bnName: 'রামগতি' },
      { name: 'Kamalnagar', bnName: 'কমলনগর' },
    ],
    'rangamati': [
      { name: 'Rangamati Sadar', bnName: 'রাঙ্গামাটি সদর' },
      { name: 'Kaptai', bnName: 'কাপ্তাই' },
      { name: 'Baghaichhari', bnName: 'বাঘাইছড়ি' },
      { name: 'Barkal', bnName: 'বরকল' },
      { name: 'Juraichhari', bnName: 'জুরাইছড়ি' },
      { name: 'Langadu', bnName: 'লংগদু' },
      { name: 'Naniarchar', bnName: 'নানিয়ারচর' },
      { name: 'Belaichhari', bnName: 'বিলাইছড়ি' },
      { name: 'Rajasthali', bnName: 'রাজস্থলী' },
      { name: 'Kawkhali (Betbunia)', bnName: 'কাউখালী (বেতবুনিয়া)' },
    ],
    'bandarban': [
      { name: 'Bandarban Sadar', bnName: 'বান্দরবান সদর' },
      { name: 'Ruma', bnName: 'রুমা' },
      { name: 'Thanchi', bnName: 'থানচি' },
      { name: 'Lama', bnName: 'লামা' },
      { name: 'Alikadam', bnName: 'আলীকদম' },
      { name: 'Rowangchhari', bnName: 'রোয়াংছড়ি' },
      { name: 'Naikhongchhari', bnName: 'নাইক্ষ্যংছড়ি' },
    ],
    'khagrachhari': [
      { name: 'Khagrachhari Sadar', bnName: 'খাগড়াছড়ি সদর' },
      { name: 'Dighinala', bnName: 'দিঘীনালা' },
      { name: 'Panchhari', bnName: 'পানছড়ি' },
      { name: 'Mahalchhari', bnName: 'মহালছড়ি' },
      { name: 'Matiranga', bnName: 'মাটিরাঙ্গা' },
      { name: 'Manikchhari', bnName: 'মানিকছড়ি' },
      { name: 'Ramgarh', bnName: 'রামগড়' },
      { name: 'Lakshmichhari', bnName: 'লক্ষ্মীছড়ি' },
      { name: 'Guimara', bnName: 'গুইমারা' },
    ],

    // ==================== রাজশাহী বিভাগ (RAJSHAHI DIVISION) ====================
    'rajshahi-city': [
      { name: 'Boalia', bnName: 'বোয়ালিয়া' },
      { name: 'Motihar', bnName: 'মতিহার' },
      { name: 'Rajpara', bnName: 'রাজপাড়া' },
      { name: 'Shah Makhdum', bnName: 'শাহ মখদুম' },
      { name: 'Chandrima', bnName: 'চন্দ্রিমা' },
      { name: 'Kashiadanga', bnName: 'কাশিয়াডাঙ্গা' },
      { name: 'Katakhali', bnName: 'কাটাখালী' },
      { name: 'Paba', bnName: 'পবা' },
      { name: 'Godagari', bnName: 'গোদাগাড়ী' },
      { name: 'Tanore', bnName: 'তানোর' },
      { name: 'Bagmara', bnName: 'বাগমারা' },
      { name: 'Durgapur', bnName: 'দুর্গাপুর' },
      { name: 'Puthia', bnName: 'পুঠিয়া' },
      { name: 'Charghat', bnName: 'চারঘাট' },
      { name: 'Bagha', bnName: 'বাঘা' },
      { name: 'Mohonpur', bnName: 'মোহনপুর' },
    ],
    'bogura': [
      { name: 'Bogura Sadar', bnName: 'বগুড়া সদর' },
      { name: 'Shajahanpur', bnName: 'শাজাহানপুর' },
      { name: 'Sherpur', bnName: 'শেরপুর' },
      { name: 'Shibganj', bnName: 'শিবগঞ্জ' },
      { name: 'Gabtali', bnName: 'গাবতলী' },
      { name: 'Kahaloo', bnName: 'কাহালু' },
      { name: 'Dhunat', bnName: 'ধুনট' },
      { name: 'Sariakandi', bnName: 'সারিয়াকান্দি' },
      { name: 'Sonatala', bnName: 'সোনাতলা' },
      { name: 'Nandigram', bnName: 'নন্দীগ্রাম' },
      { name: 'Adamdighi', bnName: 'আদমদীঘি' },
      { name: 'Dupchanchia', bnName: 'দুপচাঁচিয়া' },
    ],
    'pabna': [
      { name: 'Pabna Sadar', bnName: 'পাবনা সদর' },
      { name: 'Ishwardi', bnName: 'ঈশ্বরদী' },
      { name: 'Santhia', bnName: 'সাঁথিয়া' },
      { name: 'Chatmohar', bnName: 'চাটমোহর' },
      { name: 'Bera', bnName: 'বেড়া' },
      { name: 'Faridpur', bnName: 'ফরিদপুর' },
      { name: 'Bhangura', bnName: 'ভাঙ্গুড়া' },
      { name: 'Atgharia', bnName: 'আটঘরিয়া' },
      { name: 'Sujanagar', bnName: 'সুজানগর' },
    ],
    'sirajganj': [
      { name: 'Sirajganj Sadar', bnName: 'সিরাজগঞ্জ সদর' },
      { name: 'Belkuchi', bnName: 'বেলকুচি' },
      { name: 'Shahjadpur', bnName: 'শাহজাদপুর' },
      { name: 'Ullapara', bnName: 'উল্লাপাড়া' },
      { name: 'Kamarkhanda', bnName: 'কামারখন্দ' },
      { name: 'Kazipur', bnName: 'কাজীপুর' },
      { name: 'Raiganj', bnName: 'রায়গঞ্জ' },
      { name: 'Tarash', bnName: 'তাড়াশ' },
      { name: 'Chauhali', bnName: 'চৌহালী' },
    ],
    'naogaon': [
      { name: 'Naogaon Sadar', bnName: 'নওগাঁ সদর' },
      { name: 'Patnitala', bnName: 'পত্নীতলা' },
      { name: 'Dhamoirhat', bnName: 'ধামইরহাট' },
      { name: 'Mohadevpur', bnName: 'মহাদেবপুর' },
      { name: 'Manda', bnName: 'মান্দা' },
      { name: 'Niamatpur', bnName: 'নিয়ামতপুর' },
      { name: 'Raninagar', bnName: 'রাণীনগর' },
      { name: 'Atrai', bnName: 'আত্রাই' },
      { name: 'Badalgachhi', bnName: 'বদলগাছী' },
      { name: 'Porsha', bnName: 'পোরশা' },
      { name: 'Sapahar', bnName: 'সাপাহার' },
    ],
    'natore': [
      { name: 'Natore Sadar', bnName: 'নাটোর সদর' },
      { name: 'Singra', bnName: 'সিংড়া' },
      { name: 'Baraigram', bnName: 'বড়াইগ্রাম' },
      { name: 'Bagatipara', bnName: 'বাগাতিপাড়া' },
      { name: 'Gurudaspur', bnName: 'গুরুদাসপুর' },
      { name: 'Lalpur', bnName: 'লালপুর' },
      { name: 'Naldanga', bnName: 'নলডাঙ্গা' },
    ],
    'chapainawabganj': [
      { name: 'Chapainawabganj Sadar', bnName: 'চাঁপাইনবাবগঞ্জ সদর' },
      { name: 'Shibganj', bnName: 'শিবগঞ্জ' },
      { name: 'Gomastapur', bnName: 'গোমস্তাপুর' },
      { name: 'Nachole', bnName: 'নাচোল' },
      { name: 'Bholahat', bnName: 'ভোলাহাট' },
    ],
    'joypurhat': [
      { name: 'Joypurhat Sadar', bnName: 'জয়পুরহাট সদর' },
      { name: 'Panchbibi', bnName: 'পাঁচবিবি' },
      { name: 'Kalai', bnName: 'কালাই' },
      { name: 'Khetlal', bnName: 'ক্ষেতলাল' },
      { name: 'Akkelpur', bnName: 'আক্কেলপুর' },
    ],

    // ==================== খুলনা বিভাগ (KHULNA DIVISION) ====================
    'khulna-city': [
      { name: 'Khulna Sadar', bnName: 'খুলনা সদর' },
      { name: 'Sonadanga', bnName: 'সোনাডাঙ্গা' },
      { name: 'Khalishpur', bnName: 'খালিশপুর' },
      { name: 'Daulatpur', bnName: 'দৌলতপুর' },
      { name: 'Khan Jahan Ali', bnName: 'খান জাহান আলী' },
      { name: 'Harintana', bnName: 'হরিণটানা' },
      { name: 'Aranghata', bnName: 'আড়ংঘাটা' },
      { name: 'Dumuria', bnName: 'ডুমুরিয়া' },
      { name: 'Rupsha', bnName: 'রূপসা' },
      { name: 'Batiaghata', bnName: 'বটিয়াঘাটা' },
      { name: 'Phultala', bnName: 'ফুলতলা' },
      { name: 'Dighalia', bnName: 'দিঘলিয়া' },
      { name: 'Koyra', bnName: 'কয়রা' },
      { name: 'Paikgachha', bnName: 'পাইকগাছা' },
      { name: 'Dacope', bnName: 'দাকোপ' },
      { name: 'Terokhada', bnName: 'তেরখাদা' },
    ],
    'jashore': [
      { name: 'Jashore Sadar', bnName: 'যশোর সদর' },
      { name: 'Jhikargachha', bnName: 'ঝিকরগাছা' },
      { name: 'Chaugachha', bnName: 'চৌগাছা' },
      { name: 'Abhaynagar', bnName: 'অভয়নগর' },
      { name: 'Bagherpara', bnName: 'বাঘারপাড়া' },
      { name: 'Keshabpur', bnName: 'কেশবপুর' },
      { name: 'Manirampur', bnName: 'মণিরামপুর' },
      { name: 'Sharsha (Benapole)', bnName: 'শার্শা (বেনাপোল)' },
    ],
    'kushtia': [
      { name: 'Kushtia Sadar', bnName: 'কুষ্টিয়া সদর' },
      { name: 'Kumarkhali', bnName: 'কুমারখালী' },
      { name: 'Khoksa', bnName: 'খোকসা' },
      { name: 'Mirpur', bnName: 'মিরপুর' },
      { name: 'Bheramara', bnName: 'ভেড়ামারা' },
      { name: 'Daulatpur', bnName: 'দৌলতপুর' },
    ],
    'satkhira': [
      { name: 'Satkhira Sadar', bnName: 'সাতক্ষীরা সদর' },
      { name: 'Assasuni', bnName: 'আশাশুনি' },
      { name: 'Debhata', bnName: 'দেবহাটা' },
      { name: 'Kalaroa', bnName: 'কলারোয়া' },
      { name: 'Kaliganj', bnName: 'কালীগঞ্জ' },
      { name: 'Shyamnagar', bnName: 'শ্যামনগর' },
      { name: 'Tala', bnName: 'তালা' },
    ],
    'bagerhat': [
      { name: 'Bagerhat Sadar', bnName: 'বাগেরহাট সদর' },
      { name: 'Mongla', bnName: 'মোংলা' },
      { name: 'Fakirhat', bnName: 'ফকিরহাট' },
      { name: 'Kachua', bnName: 'কচুয়া' },
      { name: 'Mollahat', bnName: 'মোল্লাহাট' },
      { name: 'Rampal', bnName: 'রামপাল' },
      { name: 'Morrelganj', bnName: 'মোরেলগঞ্জ' },
      { name: 'Sarankhola', bnName: 'শরণখোলা' },
      { name: 'Chitalmari', bnName: 'চিতলমারী' },
    ],
    'jhenaidah': [
      { name: 'Jhenaidah Sadar', bnName: 'ঝিনাইদহ সদর' },
      { name: 'Kaliganj', bnName: 'কালীগঞ্জ' },
      { name: 'Kotchandpur', bnName: 'কোটচাঁদপুর' },
      { name: 'Maheshpur', bnName: 'মহেশপুর' },
      { name: 'Shailkupa', bnName: 'শৈলকুপা' },
      { name: 'Harinakunda', bnName: 'হরিণাকুণ্ডু' },
    ],
    'chuadanga': [
      { name: 'Chuadanga Sadar', bnName: 'চুয়াডাঙ্গা সদর' },
      { name: 'Alamdanga', bnName: 'আলমডাঙ্গা' },
      { name: 'Damurhuda', bnName: 'দামুড়হুদা' },
      { name: 'Jibannagar', bnName: 'জীবননগর' },
    ],
    'magura': [
      { name: 'Magura Sadar', bnName: 'মাগুরা সদর' },
      { name: 'Sreepur', bnName: 'শ্রীপুর' },
      { name: 'Mohammadpur', bnName: 'মোহাম্মদপুর' },
      { name: 'Shalikha', bnName: 'শালিখা' },
    ],
    'meherpur': [
      { name: 'Meherpur Sadar', bnName: 'মেহেরপুর সদর' },
      { name: 'Gangni', bnName: 'গাংনী' },
      { name: 'Mujibnagar', bnName: 'মুজিবনগর' },
    ],
    'narail': [
      { name: 'Narail Sadar', bnName: 'নড়াইল সদর' },
      { name: 'Lohagara', bnName: 'লোহাগড়া' },
      { name: 'Kalia', bnName: 'কালিয়া' },
    ],

    // ==================== বরিশাল বিভাগ (BARISHAL DIVISION) ====================
    'barishal-city': [
      { name: 'Kotwali', bnName: 'কোতোয়ালী' },
      { name: 'Airport', bnName: 'এয়ারপোর্ট' },
      { name: 'Bandar', bnName: 'বন্দর' },
      { name: 'Kaunia', bnName: 'কাউনিয়া' },
      { name: 'Babuganj', bnName: 'বাবুগঞ্জ' },
      { name: 'Bakerganj', bnName: 'বাকেরগঞ্জ' },
      { name: 'Banaripara', bnName: 'বানারীপাড়া' },
      { name: 'Gournadi', bnName: 'গৌরনদী' },
      { name: 'Hizla', bnName: 'হিজলা' },
      { name: 'Mehendiganj', bnName: 'মেহেন্দিগঞ্জ' },
      { name: 'Muladi', bnName: 'মুলাদী' },
      { name: 'Wazirpur', bnName: 'উজিরপুর' },
      { name: 'Agailjhara', bnName: 'আগৈলঝাড়া' },
    ],
    'bhola': [
      { name: 'Bhola Sadar', bnName: 'ভোলা সদর' },
      { name: 'Burhanuddin', bnName: 'বোরহানউদ্দিন' },
      { name: 'Char Fasson', bnName: 'চরফ্যাশন' },
      { name: 'Daulatkhan', bnName: 'দৌলতখান' },
      { name: 'Lalmohan', bnName: 'লালমোহন' },
      { name: 'Manpura', bnName: 'মনপুরা' },
      { name: 'Tazumuddin', bnName: 'তজুমদ্দিন' },
    ],
    'patuakhali': [
      { name: 'Patuakhali Sadar', bnName: 'পটুয়াখালী সদর' },
      { name: 'Bauphal', bnName: 'বাউফল' },
      { name: 'Dashmina', bnName: 'দশমিনা' },
      { name: 'Galachipa', bnName: 'গলাচিপা' },
      { name: 'Kalapara (Kuakata)', bnName: 'কলাপাড়া (কুয়াকাটা)' },
      { name: 'Mirzaganj', bnName: 'মির্জাগঞ্জ' },
      { name: 'Dumki', bnName: 'দুমকি' },
      { name: 'Rangabali', bnName: 'রাঙ্গাবালী' },
    ],
    'pirojpur': [
      { name: 'Pirojpur Sadar', bnName: 'পিরোজপুর সদর' },
      { name: 'Bhandaria', bnName: 'ভাণ্ডারিয়া' },
      { name: 'Mathbaria', bnName: 'মঠবাড়িয়া' },
      { name: 'Kawkhali', bnName: 'কাউখালী' },
      { name: 'Nazirpur', bnName: 'নাজিরপুর' },
      { name: 'Nesarabad (Swarupkathi)', bnName: 'নেছারাবাদ (স্বরূপকাঠি)' },
      { name: 'Indurkani', bnName: 'ইন্দুরকানী' },
    ],
    'barguna': [
      { name: 'Barguna Sadar', bnName: 'বরগুনা সদর' },
      { name: 'Amtali', bnName: 'আমতলী' },
      { name: 'Bamna', bnName: 'বামনা' },
      { name: 'Betagi', bnName: 'বেতাগী' },
      { name: 'Patharghata', bnName: 'পাথরঘাটা' },
      { name: 'Taltali', bnName: 'তালতলী' },
    ],
    'jhalokathi': [
      { name: 'Jhalokathi Sadar', bnName: 'ঝালকাঠি সদর' },
      { name: 'Kathalia', bnName: 'কাঠালিয়া' },
      { name: 'Nalchity', bnName: 'নলছিটি' },
      { name: 'Rajapur', bnName: 'রাজাপুর' },
    ],

    // ==================== সিলেট বিভাগ (SYLHET DIVISION) ====================
    'sylhet-city': [
      { name: 'Kotwali', bnName: 'কোতোয়ালী' },
      { name: 'Shah Poran', bnName: 'শাহ পরান' },
      { name: 'Airport', bnName: 'এয়ারপোর্ট' },
      { name: 'South Surma', bnName: 'দক্ষিণ সুরমা' },
      { name: 'Jalalabad', bnName: 'জালালাবাদ' },
      { name: 'Osmani Nagar', bnName: 'ওসমানী নগর' },
      { name: 'Beanibazar', bnName: 'বিয়ানীবাজার' },
      { name: 'Golapganj', bnName: 'গোলাপগঞ্জ' },
      { name: 'Companiganj', bnName: 'কোম্পানীগঞ্জ' },
      { name: 'Fenchuganj', bnName: 'ফেঞ্চুগঞ্জ' },
      { name: 'Balaganj', bnName: 'বালাগঞ্জ' },
      { name: 'Gowainghat', bnName: 'গোয়াইনঘাট' },
      { name: 'Jaintiapur', bnName: 'জৈন্তাপুর' },
      { name: 'Kanaighat', bnName: 'কানাইঘাট' },
      { name: 'Zakiganj', bnName: 'জকিগঞ্জ' },
    ],
    'moulvibazar': [
      { name: 'Moulvibazar Sadar', bnName: 'মৌলভীবাজার সদর' },
      { name: 'Sreemangal', bnName: 'শ্রীমঙ্গল' },
      { name: 'Kulaura', bnName: 'কুলাউড়া' },
      { name: 'Kamalganj', bnName: 'কমলগঞ্জ' },
      { name: 'Barlekha', bnName: 'বড়লেখা' },
      { name: 'Juri', bnName: 'জুড়ী' },
      { name: 'Rajnagar', bnName: 'রাজনগর' },
    ],
    'habiganj': [
      { name: 'Habiganj Sadar', bnName: 'হবিগঞ্জ সদর' },
      { name: 'Madhabpur', bnName: 'মাধবপুর' },
      { name: 'Chunarughat', bnName: 'চুনারুঘাট' },
      { name: 'Bahubal', bnName: 'বাহুবল' },
      { name: 'Nabiganj', bnName: 'নবীগঞ্জ' },
      { name: 'Baniachong', bnName: 'বানিয়াচং' },
      { name: 'Ajmiriganj', bnName: 'আজমিরীগঞ্জ' },
      { name: 'Lakhai', bnName: 'লাখাই' },
      { name: 'Shayestaganj', bnName: 'শায়েস্তাগঞ্জ' },
    ],
    'sunamganj': [
      { name: 'Sunamganj Sadar', bnName: 'সুনামগঞ্জ সদর' },
      { name: 'Chhatak', bnName: 'ছাতক' },
      { name: 'Jagannathpur', bnName: 'জগন্নাথপুর' },
      { name: 'Derai', bnName: 'দিরাই' },
      { name: 'Dharampasha', bnName: 'ধর্মপাশা' },
      { name: 'Dowarabazar', bnName: 'দোয়ারাবাজার' },
      { name: 'Tahirpur', bnName: 'তাহিরপুর' },
      { name: 'Jamalganj', bnName: 'জামালগঞ্জ' },
      { name: 'Shantiganj', bnName: 'শান্তিগঞ্জ' },
      { name: 'Sullah', bnName: 'শাল্লা' },
      { name: 'Bishwamvarpur', bnName: 'বিশ্বম্ভরপুর' },
      { name: 'Madhyanagar', bnName: 'মধ্যনগর' },
    ],

    // ==================== রংপুর বিভাগ (RANGPUR DIVISION) ====================
    'rangpur-city': [
      { name: 'Kotwali', bnName: 'কোতোয়ালী' },
      { name: 'Rangpur Sadar', bnName: 'রংপুর সদর' },
      { name: 'Mithapukur', bnName: 'মিঠাপুকুর' },
      { name: 'Pirganj', bnName: 'পীরগঞ্জ' },
      { name: 'Pirgachha', bnName: 'পীরগাছা' },
      { name: 'Badarganj', bnName: 'বদরগঞ্জ' },
      { name: 'Gangachhara', bnName: 'গংগাচড়া' },
      { name: 'Kaunia', bnName: 'কাউনিয়া' },
      { name: 'Taraganj', bnName: 'তারাগঞ্জ' },
    ],
    'dinajpur': [
      { name: 'Dinajpur Sadar', bnName: 'দিনাজপুর সদর' },
      { name: 'Birganj', bnName: 'বীরগঞ্জ' },
      { name: 'Biral', bnName: 'বিরল' },
      { name: 'Bochaganj', bnName: 'বোচাগঞ্জ' },
      { name: 'Fulbari', bnName: 'ফুলবাড়ী' },
      { name: 'Ghoraghat', bnName: 'ঘোড়াঘাট' },
      { name: 'Hakimpur', bnName: 'হাকিমপুর' },
      { name: 'Kaharole', bnName: 'কাহারোল' },
      { name: 'Khansama', bnName: 'খানসামা' },
      { name: 'Nawabganj', bnName: 'নবাবগঞ্জ' },
      { name: 'Parbatipur', bnName: 'পার্বতীপুর' },
      { name: 'Chirirbandar', bnName: 'চিরিরবন্দর' },
      { name: 'Birol', bnName: 'বিরামপুর' },
    ],
    'gaibandha': [
      { name: 'Gaibandha Sadar', bnName: 'গাইবান্ধা সদর' },
      { name: 'Gobindaganj', bnName: 'গোবিন্দগঞ্জ' },
      { name: 'Palashbari', bnName: 'পলাশবাড়ী' },
      { name: 'Sadullapur', bnName: 'সাদুল্লাপুর' },
      { name: 'Saghata', bnName: 'সাঘাটা' },
      { name: 'Sundarganj', bnName: 'সুন্দরগঞ্জ' },
      { name: 'Phulchhari', bnName: 'ফুলছড়ি' },
    ],
    'kurigram': [
      { name: 'Kurigram Sadar', bnName: 'কুড়িগ্রাম সদর' },
      { name: 'Nageshwari', bnName: 'নাগেশ্বরী' },
      { name: 'Bhurungamari', bnName: 'ভুরুঙ্গামারী' },
      { name: 'Chilmari', bnName: 'চিলমারী' },
      { name: 'Ulipur', bnName: 'উলিপুর' },
      { name: 'Rajarhat', bnName: 'রাজারহাট' },
      { name: 'Rowmari', bnName: 'রৌমারী' },
      { name: 'Char Rajibpur', bnName: 'চর রাজিবপুর' },
      { name: 'Phulbari', bnName: 'ফুলবাড়ী' },
    ],
    'lalmonirhat': [
      { name: 'Lalmonirhat Sadar', bnName: 'লালমনিরহাট সদর' },
      { name: 'Aditmari', bnName: 'আদিতমারী' },
      { name: 'Hatibandha', bnName: 'হাতীবান্ধা' },
      { name: 'Kaliganj', bnName: 'কালীগঞ্জ' },
      { name: 'Patgram', bnName: 'পাটগ্রাম' },
    ],
    'nilphamari': [
      { name: 'Nilphamari Sadar', bnName: 'নীলফামারী সদর' },
      { name: 'Saidpur', bnName: 'সৈয়দপুর' },
      { name: 'Domar', bnName: 'ডোমার' },
      { name: 'Dimla', bnName: 'ডিমলা' },
      { name: 'Jaldhaka', bnName: 'জলঢাকা' },
      { name: 'Kishoreganj', bnName: 'কিশোরগঞ্জ' },
    ],
    'panchagarh': [
      { name: 'Panchagarh Sadar', bnName: 'পঞ্চগড় সদর' },
      { name: 'Boda', bnName: 'বোদা' },
      { name: 'Debiganj', bnName: 'দেবীগঞ্জ' },
      { name: 'Atwari', bnName: 'আটোয়ারী' },
      { name: 'Tetulia', bnName: 'তেঁতুলিয়া' },
    ],
    'thakurgaon': [
      { name: 'Thakurgaon Sadar', bnName: 'ঠাকুরগাঁও সদর' },
      { name: 'Pirganj', bnName: 'পীরগঞ্জ' },
      { name: 'Ranisankail', bnName: 'রাণীশংকৈল' },
      { name: 'Baliadangi', bnName: 'বালিয়াডাঙ্গী' },
      { name: 'Haripur', bnName: 'হরিপুর' },
    ],

    // ==================== ময়মনসিংহ বিভাগ (MYMENSINGH DIVISION) ====================
    'mymensingh-city': [
      { name: 'Kotwali', bnName: 'কোতোয়ালী' },
      { name: 'Muktagachha', bnName: 'মুক্তাগাছা' },
      { name: 'Trishal', bnName: 'ত্রিশাল' },
      { name: 'Bhaluka', bnName: 'ভালুকা' },
      { name: 'Fulbaria', bnName: 'ফুলবাড়ীয়া' },
      { name: 'Gaffargaon', bnName: 'গফরগাঁও' },
      { name: 'Gauripur', bnName: 'গৌরীপুর' },
      { name: 'Haluaghat', bnName: 'হালুয়াঘাট' },
      { name: 'Ishwarganj', bnName: 'ঈশ্বরগঞ্জ' },
      { name: 'Nandail', bnName: 'নান্দাইল' },
      { name: 'Phulpur', bnName: 'ফুলপুর' },
      { name: 'Tara Khanda', bnName: 'তারাকান্দা' },
      { name: 'Dhobaura', bnName: 'ধোবাউড়া' },
    ],
    'jamalpur': [
      { name: 'Jamalpur Sadar', bnName: 'জামালপুর সদর' },
      { name: 'Baksiganj', bnName: 'বকশীগঞ্জ' },
      { name: 'Dewanganj', bnName: 'দেওয়ানগঞ্জ' },
      { name: 'Islampur', bnName: 'ইসলামপুর' },
      { name: 'Madarganj', bnName: 'মাদারগঞ্জ' },
      { name: 'Melandaha', bnName: 'মেলান্দহ' },
      { name: 'Sarishabari', bnName: 'সরিষাবাড়ী' },
    ],
    'netrokona': [
      { name: 'Netrokona Sadar', bnName: 'নেত্রকোণা সদর' },
      { name: 'Kendua', bnName: 'কেন্দুয়া' },
      { name: 'Atpara', bnName: 'আটপাড়া' },
      { name: 'Barhatta', bnName: 'বারহাট্টা' },
      { name: 'Durgapur', bnName: 'দুর্গাপুর' },
      { name: 'Kalmakanda', bnName: 'কলমাকান্দা' },
      { name: 'Madan', bnName: 'মদন' },
      { name: 'Mohanganj', bnName: 'মোহনগঞ্জ' },
      { name: 'Purbadhala', bnName: 'পূর্বধলা' },
      { name: 'Khaliajuri', bnName: 'খালিয়াজুড়ী' },
    ],
    'sherpur': [
      { name: 'Sherpur Sadar', bnName: 'শেরপুর সদর' },
      { name: 'Nalitabari', bnName: 'নালিতাবাড়ী' },
      { name: 'Nakla', bnName: 'নকলা' },
      { name: 'Jhenaigati', bnName: 'ঝিনাইগাতী' },
      { name: 'Sreebardi', bnName: 'শ্রীবরদী' },
    ],
  }
};